name: CI/CD - Type Check & Lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  backend-checks:
    name: Backend - Type Check & Lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: TypeScript compilation check
        run: npm run build

      - name: Check for TypeScript errors
        run: npx tsc --noEmit --pretty

  frontend-checks:
    name: Frontend - Type Check & Lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: ESLint check
        run: npm run lint

      - name: TypeScript compilation check
        run: npx tsc --noEmit --pretty

      - name: Build check
        run: npm run build

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [backend-checks, frontend-checks]
    if: always()

    steps:
      - name: Check job status
        run: |
          if [[ "${{ needs.backend-checks.result }}" == "failure" || "${{ needs.frontend-checks.result }}" == "failure" ]]; then
            echo "❌ CI checks failed"
            exit 1
          else
            echo "✅ All CI checks passed"
          fi
